development: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password:
  host: db

test: &test
  <<: *default
  database: acessoajustica_test

cucumber:
  <<: *test
